import pytest
from telebot_components.form.form import Form

from telebot_components.form.field import PlainTextField


DUMMY_FORM_FIELD_KW = {"required": True, "query_message": "aaa", "empty_text_error_msg": "fail :("}


@pytest.mark.parametrize(
    "fields, expected_globally_required, expected_result_type, expected_graph",
    [
        pytest.param(
            [
                PlainTextField(name="a", **DUMMY_FORM_FIELD_KW),  # type: ignore
                PlainTextField(name="b", **DUMMY_FORM_FIELD_KW),  # type: ignore
                PlainTextField(name="c", **DUMMY_FORM_FIELD_KW),  # type: ignore
            ],
            {"a", "b", "c"},
            '''
            class MyFormResultT(TypedDict):
                """Generated by Form.generate_result_type() method"""
                a: str
                b: str
                c: str
            ''',
            '''
            ┌─────┐ 
            │  a  │ 
            └─────┘ 
               |    
               V    
            ┌─────┐ 
            │  b  │ 
            └─────┘ 
               |    
               V    
            ┌─────┐ 
            │  c  │ 
            └─────┘ 
               |    
               V    
            ┌─────┐ 
            │ END │ 
            └─────┘
            ''',
            id="basic linear form"
        )
    ],
)
def test_form_graph_analysis(fields: list[PlainTextField], expected_globally_required: set[str]) -> None:
    f = Form(fields=fields)
    assert f.globally_required_fields is not None
    assert f.globally_required_fields == expected_globally_required

    print(f.generate_result_type())

    f.print_graph()

    assert False
